# Utilitzem l'imatge de nginx 
FROM nginx:latest

# Creem el volum per al fitxer default.conf
VOLUME /home/kalitoni/Examen_PPS/default.conf /etc/nginx/conf.d/default.conf

# Que utilitze el port 80
EXPOSE 80